uint8 EPEND_TIME=0
uint8 EPEND_PLAN_DURATION=1
uint8 EPEND_PLAN_LENGTH=2

uint64 num_evals

uint8 episode_end_param
float64 episode_duration  # in seconds for EPEND_TIME/EPEND_PLAN_DURATION, in rad/m for EPEND_PLAN_LENGTH
int32 starting_index
bool randomize_plants
geometry_msgs/Point min_point
geometry_msgs/Point max_point
float64 min_dist
bool with_trolley # ignores episode duration, use trolley parameters instead
---
bool success
